About
devilsec/website pull request #17
Opened 2022-05-01 21:13 UTC by Nightfire-0x07

2022-05-01 21:44 UTC, daylamtayari requested changes
So overall looks good, two minor issues that need fixing that I mentioned.
Also remove the changes to the `package-lock.json`, the version you included strips it from it's integrity and resolved endpoint.

Otherwise, concerning the actual design of the page - I think that having the title and name on two separate lines would be better.
i.e. 
> President:
> Bash
Additionally, I think you should ask folks in Discord if we would want people's real names to be included and also if we want to have an image with each person (could be a photo or just a profile pic). 

Concerning the content, it looks good but I think that it would be good to get all of the staff's thoughts on it just because it will be the main about page for the entire club.

2022-05-01 21:44 UTC, daylamtayari commented on webpack.common.js
> +    console.log(typeof(name))
These changes were made when you were debugging local node issues.
Remove them since you resolved the issue locally and they are no longer needed.

2022-05-01 21:44 UTC, daylamtayari commented on src/pages/about.html
> +<<!DOCTYPE html>
Issue caused by typo. 
Should be `<!DOCTYPE HTML>`, you have two left arrows `<<`.

2022-05-01 21:44 UTC, daylamtayari commented on src/pages/about.html
> +            DevilSec holds weekly formal meetings throughout the Fall and Spring semester that cover a range of topics starting from using a virtual machine with Linux, to learning different tools su
> Fall and Spring semester
should be "semesters"

2022-05-09 00:34 UTC, daylamtayari commented on webpack.common.js
> -    const name=item.split((__dirname+'/src/pages/')).at(-1).split('.')[0];
You removed the `console.log` statement but also removed this line which you shouldn't have since it also breaks the build.

2022-05-12 18:36 UTC, KyleMuncie submitted a review, later dismissed
Looks fine to me. If anything, I think that the "Current Leadership" part could have a different layout

2022-05-15 12:12 UTC, daylamtayari approved these changes
Well done on this page.
I am approving it because there are no issues with the page itself.

I do however, think that the way the profiles are arranged to be in a horizontal sense.
As in have the categories and then their members right underneath, making it clearer and also in my opinion looking better. 
I have attached an image of what I am talking about.

![image](https://user-images.githubusercontent.com/58621925/168472140-cec7766d-4d39-4f72-84a5-b3d07909f48b.png)

I wonder what you think and consult others about it and if you do want to implement that change, say so, so we can hold off on merging it right now.

2022-05-15 12:18 UTC, daylamtayari commented
Also I want to add two things:
- The default profile icon of the DevilSec logo is not the same size as those with images so that would be something to resolve.
- I think that adding social icons below each profile/picture would be a good addition. Can be just the Twitter, LinkedIn, GitHub and maybe each person's website.

2022-05-18 07:09 UTC, merged